openapi: 3.0.0
info:
  title: Task service
  description: Task service
  version: '1.0'

servers:
  - url: http://localhost:8080
    description: Local server for debugging

components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer

security:
  - bearer: []

paths:
  /tasks:
    $ref: 'tasksRequests.yaml#/tasks'
#  /tasks/add:
#    $ref: 'tasksRequests.yaml#/task'
  /tasks/{task_id}:
    $ref: 'tasksRequests.yaml#/task'
